version: "3.8"

services:
  server:
    image: spendsenseapi:latest
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    container_name: spendsenseapi
    hostname: spendsenseapi
    restart: on-failure
    volumes:
      - ../:/app
    ports:
      - 8506:80
    networks:
      spendsense:
        ipv4_address: 172.11.0.2

  postgresdb:
    image: postgres:15-alpine
    container_name: spendsensedb
    hostname: spendsensedb
    restart: on-failure
    ports:
      - 5434:5432
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file: ../.env
    networks:
      spendsense:
        ipv4_address: 172.11.0.3

networks:
  spendsense:
    ipam:
      config:
        - subnet: 172.11.0.0/16
          ip_range: 172.11.5.0/24
          gateway: 172.11.0.1
